### ISSUE TITLE
Handle audio-only segments

### ISSUE THREAD

**Issue by iameli** [livepeer/lpms#203] opened 2020-08-10 21:30 UTC
### Current Behavior

Sometimes Livepeer is sent audio-only segments. This could happen for a variety of reasons. In the case of MistServer, it happens when a transcode is enabled and there is more audio data in the buffer than video data. It could also happen in a variety of edge cases where bandwidth is severely constrained and end-user client software decides to only send audio to keep _something_ online. (I'm especially here thinking about livestreams from protests and whatnot — audio is better than nothing!)

Currently, we barf back a not-very-descriptive error in these cases:

```
orchestrator.go:520] Error transcoding manifestID=redacted segNo=1 segName= - Unsupported input pixel format 
segment_rpc.go:174] Could not transcode manifestID=redacted seqNo=1 err=Unsupported input pixel format 
```

This error gets bubbled back up to the broadcaster and incoming HTTP ingest segments get rejected. Instead of a contiguous audio stream with temporarily paused video, viewers see nothing until the next video segment arrives. In the MistServer case, Mist retries the transcode several times on several broadcasters and eventually gives up on the stream session entirely, causing a break in the recording if that's enabled. No good!

### Desired Behavior

Instead of erroring on such segments, let's accept them and send back audio-only tracks. The audio output should be exactly the same as the audio input. We handle one-frame segments great these days... now we just need to handle zero-frame segments.

### Concerns

Presumably the pixel count of an audio-only segment is zero. I'm slightly worried about a DoS attack against orchestrators here? If I spam a public orchestrator with high-bitrate audio, could I saturate their bandwidth and take down the orchestrator without paying the orchestrator at all? Concerning. Perhaps a cap on audio bitrate?

### Alternatives

I think the dream is that such segments could be handled on the _broadcaster_, rather than the transcoder. It's not as if the OT is actually doing anything in this case. But I imagine that would require a lot more video introspection on the B than we're currently doing, so I figure this is a quicker fix.

**Comment by darkdarkdragon** [comment] 2020-08-10 22:51
> Instead of erroring on such segments, let's accept them and send back audio-only tracks. 

Given LPMS code, for example:
```c
  // add video stream if input contains video
  inp_has_stream = ictx->vi >= 0;
  if (inp_has_stream && !octx->dv) {
    ret = add_video_stream(octx, ictx);
    if (ret < 0) em_err("Error adding video stream\n");
  }
```
LPMS should've handled this case, so we can consider this to be a bug in LPMS

>  If I spam a public orchestrator with high-bitrate audio, could I saturate their bandwidth and take down the orchestrator without paying the orchestrator at all?

You don't need anything special to do such Dos attack both on [broadcaster](https://github.com/livepeer/go-livepeer/issues/1523) and on orchestrator:

https://github.com/livepeer/go-livepeer/blob/e01f0ea63beaa68c599241533f32ae876b021911/server/segment_rpc.go#L93-L94

**Comment by iameli** [comment] 2020-08-10 23:44
Heh, fair enough.

**Comment by jailuthra** [comment] 2020-08-14 21:38
I tried reproducing this issue by sending an audio-only segment via the following testcase:
```go
func TestTranscoder_AudioOnly(t *testing.T) {
	// Reproducing #203
	run, dir := setupTest(t)
	//defer os.RemoveAll(dir)
	cmd := `
    # run segmenter and sanity check frame counts . Hardcode for now.
    ffmpeg -loglevel warning -i "$1"/../transcoder/test.ts -c:a copy -c:v copy -f hls test.m3u8
    ffprobe -loglevel warning -select_streams v -count_frames -show_streams test0.ts | grep nb_read_frames=120
    ffprobe -loglevel warning -select_streams v -count_frames -show_streams test1.ts | grep nb_read_frames=120
    ffprobe -loglevel warning -select_streams v -count_frames -show_streams test2.ts | grep nb_read_frames=120
    ffprobe -loglevel warning -select_streams v -count_frames -show_streams test3.ts | grep nb_read_frames=120

    # change frame 2 to audio-only
    ffmpeg -loglevel warning -i test2.ts -c:a copy -vn test02.ts
    mv test02.ts test2.ts
  `
	run(cmd)

	tc := NewTranscoder()
	defer tc.StopTranscoder()

	prof := P144p30fps16x9
	// Test encoding
	for i := 0; i < 4; i++ {
		in := &TranscodeOptionsIn{
			Fname: fmt.Sprintf("%s/test%d.ts", dir, i),
			Accel: Software,
		}
		out := []TranscodeOptions{{
			Oname:   fmt.Sprintf("%s/out%d.ts", dir, i),
			Profile: prof,
			Accel:   Software,
		}}
		_, err := tc.Transcode(in, out)
		if err != nil {
			t.Error(err)
		}
	}
}
```

I got a different error `E0815 02:51:28.649954   13304 ffmpeg.go:352] Transcoder Return : Invalid data found when processing input` from the one mentioned in the original post. This is an internal ffmpeg error [`AV_INVALIDDATA`](https://github.com/livepeer/lpms/blob/master/ffmpeg/ffmpeg_errors.h#L18) passed on up-the-chain.

I will try to mitigate this error as well, but to solve the original issue for MistServer in particular @iameli it would be great to have some failing sample from the Mist logs if it's possible :)

I suspect the MistServer's audio-only samples do have a video stream but is malformed in some way and thus the 'invalid pixel format' error generated probably while opening the input [here](https://github.com/livepeer/lpms/blob/master/ffmpeg/lpms_ffmpeg.c#L388)

**Comment by iameli** [comment] 2020-08-17 02:47
@jailuthra Here's an example segment. I think it self-identifies as containing both video and audio but doesn't contain actual video frames? https://storage.googleapis.com/docs.livepeer.live/eli/segment-debugging/no-audio.ts

**Comment by jailuthra** [comment] 2020-08-17 07:42
Thanks @iameli! Yup seems like there is a video stream but no frames.

In the fix I'll mitigate this case only for now as no video-stream at all should still be (a better worded) error.

**Comment by iameli** [comment] 2020-08-17 07:56
Arguably it should be an error down here, but if we can just pass through the segments for now that'll take care of the current audio-only cases. The more robust solution is potentially take care of this case in the broadcaster, but this'll take care of things for now.

**Comment by jailuthra** [comment] 2020-08-17 08:35
Weird, I've been [unable to reproduce](https://github.com/livepeer/lpms/commit/61adc069aada3709339f8b0dc84c258b9ddbba9e) the `Unsupported input pixel format` error successfully on both CPU and Nvidia :/
The 0-frame segment I've created looks exactly like the one you shared with a valid video-stream but no frames, and yet both CPU & Nvidia can transcode it without errors.

A blind short-term fix would be to simply disable the `lpms_ERR_INPUT_PIXFMT` error here https://github.com/livepeer/lpms/blob/master/ffmpeg/lpms_ffmpeg.c#L388 and see if that fixes the production erorrs. But I am not sure what side effects could be caused by that, and thus wanted to reproduce the issue and narrow the fix down to only 0-frame segments. What do you think should we do?

> The more robust solution is potentially take care of this case in the broadcaster
Yep that sounds much better as a long-term fix!

**Comment by yondonfu** [comment] 2020-08-17 13:47
> The 0-frame segment I've created looks exactly like the one you shared with a valid video-stream but no frames, and yet both CPU & Nvidia can transcode it without errors.

Is the same true of the segment at https://storage.googleapis.com/docs.livepeer.live/eli/segment-debugging/no-audio.ts that Eli shared?

Does sending the segment at https://storage.googleapis.com/docs.livepeer.live/eli/segment-debugging/no-audio.ts into prod orchestrators re-produce this issue?

**Comment by jailuthra** [comment] 2020-08-17 13:57
@yondonfu Yep pinging the segment (both Eli's and the one I created through the testcase) to a prod orchestrator reproduced the fix! (Thanks to Eli for helping me out on how to send the segment to the prod api using curl)

I did further debugging since then and this is what I've found till now:
1. Issue is only reproducible with Nvidia (and not CPU)
2. Issue is only reproducible if the *first segment* of a *transcoding session* is the one with 0-frames. If a non-first segment is 0-frames, the transcoder assumes it's pixel format etc. are OK.
3. This is the line that triggers the check/error (and not the one I was suspecting before): https://github.com/livepeer/lpms/blob/master/ffmpeg/lpms_ffmpeg.c#L879

The fix would be a bit tricky as we still would like to throw an error for unknown pixel formats. There doesn't seem to be a straightforward way to know that the stream as-a-whole is valid and just this one segment (which somehow landed on an orchestrator with a new session) has 0-frames so we can ignore the invalid pixel format.

Will think a bit more and try to patch it soon!

**Comment by iameli** [comment] 2020-08-18 05:34
Ahhh, that makes sense that it'd be confusing how to handle the first segment of a session.

Is there a way to differentiate the "unknown" vs "absent" values of `ic->streams[ctx->vi]->codecpar->format`?

**Comment by jailuthra** [comment] 2020-08-18 07:38
>  "unknown" vs "absent" 

Yep this was not the hard part as checking if a stream exists && the pixel format is `AV_PIX_FMT_NONE` matches with our case.

But checking this and disabling the error in the `open_video_decoder` function was not enough as a lot of places in the Cgo code assume a valid stream with non-zero width/height.

Manually setting the state to treat the video txcoding process as `copy` did work **but** then it copied subsequent segments as well with scaling them down (those that had video frames). It's very hard easy to change the state of the transcoder between segments in an `online` session.

Right now I'm trying to bypass calling the Cgo `lpms_transcode` altogether for the initial n-segments that have 0-frame. And manually copy the `.ts` file in the Go module's [transcode function](https://github.com/livepeer/lpms/blob/master/ffmpeg/ffmpeg.go#L174) itself. Then as soon as we see the first segment in a session that has non-zero frames, we can send it off the the Cgo module.

**Comment by darkdarkdragon** [comment] 2020-08-18 15:58
> Right now I'm trying to bypass calling the Cgo lpms_transcode altogether for the initial n-segments that have 0-frames

How will you find out that segment have 0-frames without calling C code?

**Comment by jailuthra** [comment] 2020-08-18 16:18
> How will you find out that segment have 0-frames without calling C code?

Yep @darkdarkdragon my bad, realized that in 10 mins after writing that comment xD

So current status is that a hotfix is out: https://github.com/livepeer/lpms/commit/e7be29043f8e446b68ce94f541e95eac995b1a20
1. The go transcode function uses the `ffprobe` binary to check if the first segment(s) are no-video-frame ones
2. If it is, it manually changes the output parameters to force `copy` codec for audio/video and calls `tc.Transcode` again (which will in turn call Cgo like usual)
3. As soon as we see a normal segment we turn back to normal transcoding

**Current problems:**
* Can't depend on `ffprobe` binary being available for the public release. But should be ok for our own deployment if we wanna push it asap. I am currently working on creating a new function in the Cgo module using the ffmpeg C api to do all of this without `ffprobe`.
* Some cleanup remaining.

**Closed** 2020-08-24 11:36 UTC
