### ISSUE TITLE
CircleCI failing on `segmenter` tests

### ISSUE THREAD

**Issue by jailuthra** [livepeer/lpms#278] opened 2021-12-07 16:19 UTC
Since last week our CI pipeline fails on `TestSegmenter` unit test here https://github.com/livepeer/lpms/blob/1b6c4df523c2523d5309cd0fe9e7c518811ea779/segmenter/video_segmenter_test.go#L134-L138

Nothing obvious has changed on the segmenter codebase recently, so I suspect something changed in the environment (i.e. CircleCI, Golang, RTMP port?) that is causing this.

**Comment by yondonfu** [comment] 2021-12-20 19:26
Let's determine if this is a problem with CircleCI vs. a problem with the tests/code.

If the problem is with the tests/code let's fix it.

If the problem is with CircleCI I suggest we look into https://github.com/livepeer/lpms/issues/284

**Comment by yondonfu** [comment] 2021-12-30 14:31
Closed by #286

**Closed by yondonfu** 2021-12-30 14:31 UTC
